name: Share data between Job

on: [push]

jobs:
  phase_i:
    name: Exporting Path
    runs-on: ubuntu-latest
    steps: 
      - shell: bash
        run: |
          echo "Hello World"
            
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: java app.java
      - run: |
          java -version > version.txt
          which java > which.txt
      - run: |
          cat version.txt
          cat which.txt
      - name: Upload txt
        uses: actions/upload-artifact@v3
        with:
          name: java path
          path: which.txt

  phase_ii:
    name: Importing Path
    needs: phase_i
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: java path
          
      - name: declare_var
        run: |
          variable=$(cat which.txt)
          echo "$variable"
  
